inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  NewCops: enable

Layout/ExtraSpacing:
  AllowForAlignment: true

Lint/UnusedMethodArgument:
  Exclude:
    - 'domain/fundraising_events/data_gateways/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/domain/_features/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/domain/_features/*'

Style/Documentation:
  Exclude:
    - 'spec/**'
