require: rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable

Layout/ExtraSpacing:
  AllowForAlignment: true

Lint/UnusedMethodArgument:
  Exclude:
    - "domain/fundraising_events/data_gateways/*"

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for

RSpec/DescribeClass:
  Exclude:
    - "spec/domain/_features/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/domain/_features/**/*"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/domain/_features/**/*"

Style/Documentation:
  Exclude:
    - "spec/**"

Style/KeywordParametersOrder:
  Exclude:
    - "domain/fundraising_events/entities/*"
